### ISSUE TITLE
Crashes on Galileo when calling readHeader() or skipResponseHeaders()

### ISSUE THREAD

**Issue by mechalas** [amcewen/HttpClient#10]
This library crashes on Galileo when you call skipResponseHeaders() or readHeader(). The issue is that readHeader() is doing this:

if (*iContentLengthPtr == c)

But this pointer gets initialized to 0 instead of kContentLengthPrefix in resetState(), so you are doing a check on a NULL pointer. On a true Arduino device this may not crash, but I bet it doesn't work like it's intended.

The fix is to initialize iContentLengthPtr correctly in resetState():

iContentLengthPtr= kContentLengthPrefix;

**Comment by mechalas** [comment]
Yes, this really does run on Galileo if you make this change.

Are you sure your crash is due to this issue, and not some other problem?

**Comment by amcewen** [comment]
Fix released in version 2.2.0, which should soon be available via the new Arduino library manager
