### ISSUE TITLE
Do we really need to derive Client class?

### ISSUE THREAD

**Issue by honteng** [amcewen/HttpClient#17]
Thank you for such a great library. This library helps a lot to make IoT devices very easily.

So I tried to use this library for CC3200 on Energia, but it doesn't work well, because Client class is different from Arduino. Client class of CC3200 needs to implement SSL related pure virtual methods, so HttpClient class instantiation fails. If HttpClient class derives from WiFiClient, it does work.

But I wonder wonder why HttpClient has to derive from Client class? IMHO, Client class is for TCP layer class and HttpClient class is upper layer. So this is not a "is-a" relation, but "has-a" relation, right? Or is there anything rational the class has to inherit?

I've been working on general C++ projects for a while but not much about Arduino projects. If I would miss something, please let me know.

Thanks,

**Comment by amcewen** [comment]
The main reason it inherits from Client is to provide a familiar interface for anyone working with it.  It definitely needs to derive from Stream, but `stop()`, `connected()` and `bool()` are useful from Client.

However, do you really need it to derive from WiFiClient to get it to work?  There is a pull request which claims to work with the Energia, but I don't have one to test with - see https://github.com/amcewen/HttpClient/pull/14 for details.
