### ISSUE TITLE
finishRequest()?

### ISSUE THREAD

**Issue by vicary** [amcewen/HttpClient#24]
I have been trying to make a POST request in JSON format, but with no luck. Server never treats my request as finished and halts until TCP timeout.

Here is what I've learnt by reading the code:

1. I need to add Content-Type and Content-Length headers
1. I must call `beginRequest()` to prevent `finishHeaders()` in `post()`
1. I must call `endRequest()` before POST body
1. I should call `finishRequest()` after POST body

I stuck in step 4 because `finishRequest()` is mentioned in header but not implemented. According to header comments I simply added `iClient->println();` for that.

But the server is still not responding, not even treated it as a finished request.

Any ideas?

**Comment by vicary** [comment]
Figured out, closing.

**Comment by weberc2** [comment]
@vicary I'm running into the same issue. How did you resolve?

**Comment by vicary** [comment]
@weberc2 I have moved on to Raspberry Pi projects for years, sorry I didn't keep anything.

Guessing from my own habit, if I was closing without further explanations, it should be something obvious and I was feeling dumb.

Hope it gives you some clue to start with.
